changing name
michalinadengusiak/Learning-Python pull request #3
Opened 2018-10-20 19:43 UTC by michalinadengusiak

_I have completed task_ #1  _!!!!!_

@FraserGreenroyd 

![image](https://user-images.githubusercontent.com/37042279/47259877-d6ed2b00-d4b0-11e8-86da-680940516b41.png)
_How can we/ Do we need to solve the_ **red lines**?

2018-10-22 13:38 UTC, FraserGreenroyd requested changes
Functionality looks ok, just some formatting and maintaining comments needed to do it right from the off :smile:

2018-10-22 13:38 UTC, FraserGreenroyd commented on Python scripts/Python Hangman game withoutdrawing.py
> +
There are no comments in this file for maintainers to later use to remind anyone of what the desired functionality was here.

I'd like to see some comments and some slightly better formatting - there's a lot of blank lines included at the top of the file and not very many in the core `while` loop. I'd recommend no more than 1 blank line between code, but to add some after the empty `print` statement.

2018-10-22 15:19 UTC, FraserGreenroyd commented
Also, if you wish to close #1 when this PR is resolved, you need to use the `Fixes` keyword - e.g. `Fixes #1`

Additionally, even though I have provided a review requesting changes it is still allowing us to merge the PR without the review being done. You need to add branch protection to the repository. This can be found by going to the settings -> branch protection and setting some rules for the `master` branch. :smile:

2018-10-23 06:37 UTC, michalinadengusiak commented
@FraserGreenroyd 
Finished your second comment, one to go!

2018-10-23 16:05 UTC, michalinadengusiak commented
@FraserGreenroyd 
Fixed all your comments, please review again :stuck_out_tongue_winking_eye:

2018-10-23 16:19 UTC, FraserGreenroyd commented
@michalinadengusiak I'm not seeing any changes to the actual `.py` file that I commented on? Did you push the changes for that file or just the notebook files?

2018-10-23 16:30 UTC, FraserGreenroyd approved these changes
Great work, comments resolved, happy to be merged :smile:

2018-10-23 16:31 UTC, michalinadengusiak commented
@FraserGreenroyd 
Which of the three options should I use?

2018-10-23 16:39 UTC, FraserGreenroyd commented
@michalinadengusiak all three will work, it depends entirely on what you want to achieve.

I would recommend strongly that you **never** squash and merge because it removes some commit history.

Either merge it, or rebase and merge it, both are equally good though merge provides additional commit history.

Rebase and merge is what your dad and I have to do at work, but the final choice is up to you :smile:

2018-10-23 16:44 UTC, merged